name: ${project.parent.name}
main: de.erethon.dungeonsxl.DungeonsXL
version: ${project.parent.version}${buildNo}
authors: [Frank Baumann, Milan Albrecht, Tobias Schmitz, Daniel Saukel]
description: ${project.parent.description}
website: ${project.parent.url}
depend: [ItemsXL]
softdepend: [CommandsXL, ItemsXL, Vault, Citizens, CustomMobs, InsaneMobs, MythicMobs, HolographicDisplays, LWC, PlaceholderAPI, Parties, Multiverse-Inventories]
commands:
  dungeonsxl:
    description: Reference command for DungeonsXL.
    aliases: [dxl,dungeon]
api-version: 1.13
